# Generated by Django 4.2.3 on 2023-11-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userprofile_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='number',
            new_name='mobile',
        ),
    ]
