# Generated by Django 4.2.3 on 2023-11-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_faq_serialnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='serialnumber',
        ),
        migrations.AddField(
            model_name='product',
            name='serialnumber',
            field=models.IntegerField(default=0),
        ),
    ]
