# Generated by Django 4.2.3 on 2023-11-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_faq_serialnumber_product_serialnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='productserial',
            new_name='serialnumber',
        ),
    ]
