# Generated by Django 4.2.3 on 2023-11-01 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_productserial_checkout_serialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='userprofile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.userprofile'),
            preserve_default=False,
        ),
    ]
