# Generated by Django 4.2.3 on 2023-11-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_product_detail_remove_product_flag_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
