# Generated by Django 4.2.3 on 2023-11-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_checkout_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='serialnumber',
        ),
        migrations.AddField(
            model_name='checkout',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
    ]
