# Generated by Django 4.2.3 on 2023-11-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_checkout_serialnumber_checkout_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
