# Generated by Django 4.2.3 on 2023-11-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_product_category_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
