# Generated by Django 4.2.3 on 2023-11-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_checkout_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
