# Generated by Django 4.2.3 on 2023-11-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_checkout_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
