# Generated by Django 4.2.3 on 2023-11-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_detailoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='info',
        ),
    ]
