# Generated by Django 4.2.3 on 2023-11-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_brand_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fullname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
