# Generated by Django 4.2.3 on 2023-11-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_product_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fullname',
            field=models.TextField(max_length=2000),
        ),
    ]
