# Generated by Django 4.2.3 on 2023-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_product_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nrate',
            field=models.IntegerField(default=0),
        ),
    ]
