# Generated by Django 4.2.3 on 2023-11-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_comment_user_alter_faq_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replyto',
        ),
        migrations.AddField(
            model_name='comment',
            name='replytoproduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='serialofcomment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='serialtocomment',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
