# Generated by Django 4.2.3 on 2023-11-06 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_remove_comment_replyto_comment_replytoproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='serialtocomment',
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialtofaq', models.IntegerField(default=0)),
                ('serialoffaq', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=2000)),
                ('rate', models.IntegerField(default=5)),
                ('rateoffaq', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('replytoproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
