# Generated by Django 4.2.3 on 2023-11-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_comment_serialtocomment_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='name',
            new_name='title',
        ),
    ]
