# Generated by Django 4.2.3 on 2023-11-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_address_block_address_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='default',
            field=models.IntegerField(default=0),
        ),
    ]
