# Generated by Django 4.2.3 on 2023-11-09 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_address_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=100)),
                ('barcode', models.ImageField(upload_to='Payaddress')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payaddress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.payaddress'),
            preserve_default=False,
        ),
    ]
