# Generated by Django 4.2.3 on 2023-11-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_payaddress_userprofile_payaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='payaddress',
        ),
    ]
