# Generated by Django 4.2.3 on 2023-11-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_remove_userprofile_payaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payaddress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.payaddress'),
            preserve_default=False,
        ),
    ]
