# Generated by Django 4.2.3 on 2023-11-13 12:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_product_present_product_specialpresent'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='img',
            field=models.ImageField(default=1, upload_to='brands_img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='article',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
