# Generated by Django 4.2.3 on 2023-11-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_brand_img_alter_brand_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
