# Generated by Django 4.2.3 on 2023-11-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_userprofile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='block',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='familyofreceiver',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='nameofreceiver',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='pelak',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=200),
        ),
    ]
